name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        aws-access-key-id: AKIASUBPVZPZQDVCQQBR
        aws-secret-access-key: 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
        aws-region: ap-northeast-1
    - name: Build the Docker image
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 180488621043.dkr.ecr.ap-northeast-2.amazonaws.com
        docker build -t findcode_docker_test .
        docker tag findcode_docker_test:latest 180488621043.dkr.ecr.ap-northeast-2.amazonaws.com/findcode_docker_test:latest
        docker push 180488621043.dkr.ecr.ap-northeast-2.amazonaws.com/findcode_docker_test:latest
