name: AWS Lambda Deployment

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: findcode_docker_test
  LAMBDA_FUNCTION_NAME: lambda-docker

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: AWS CLI
      uses: aws-actions/aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Push Docker image to Amazon ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

    - name: Update AWS Lambda function
      id: update-lambda
      uses: aws-actions/aws-cli@v1
      with:
        args: lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --image-uri ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

